config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/about', to: 'pages#about'

  devise_for :users, skip: :registrations do
    delete '/logout', to: 'sessions#destroy', as: :destroy_user_session
    get '/login', to: 'sessions#new', as: :new_user_session
    post '/login', to: 'sessions#create', as: :user_session
  end
  devise_for :doners, controllers: { registrations: 'doner/registrations' }, skip: :sessions
  devise_for :super_admins, skip: :sessions
  resources :dashboards
  resources :foods
  get '/assign', to: 'foods#assign'
  patch '/assign', to: 'foods#assign_food'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doner.rb
class Doner < User
  validates :first_name, :phone, presence: true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  validates :name, :phone, :address, :description, :number_of_plate, presence: true
end

app/models/super_admin.rb
class SuperAdmin < User
  validates :first_name, :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create_commit :send_credential

  def doner?
    type == 'Doner'
  end
  def super_admin?
    type == 'SuperAdmin'
  end

  def send_credential
    # Here goes email for this user for this need sendGrid service credential
    # return if Rails.env.development?
    # UserMailer.user_welcome(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource_or_scope)
    dashboards_path
  end
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,
        keys: [:first_name, :last_name, :phone, :email, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:sign_in,
        keys: [:email, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:account_update,
        keys: [:first_name, :last_name, :phone, :email, :password, :password_confirmation])
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!  

  def index
    if current_user.super_admin?
      @foods = Food.all
    else
      @foods = Food.where(user_id: current_user.id)
    end
  end
end
  

app/controllers/doner/registrations_controller.rb
# frozen_string_literal: true

class Doner::RegistrationsController < Devise::RegistrationsController

  def after_sign_up_path_for(resource)
    dashboards_path
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!  
  before_action :set_food, only: [:show, :edit, :assign, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    if current_user.super_admin?
      @foods = Food.all
    else
      @foods = Food.where(user_id: current_user.id)
    end
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Request created successfully.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def assign
    @food = Food.find(params[:id].to_i)
  end

  def assign_food
    if food_params[:assigned_user].present?
      @food = Food.find(food_params[:id].to_i)
      if @food.present?
        @food.status = true
        @food.assigned_user = food_params[:assigned_user]
        @food.save
        @food_req_user = Food.where(name: food_params[:assigned_user]).first
        @food_req_user.status = true
        @food_req_user.assigned_user = @food.name
        @food_req_user.save
      end
      respond_to do |format|
        format.html { redirect_to foods_url, notice: 'Food assigned successfully' }
        format.json { head :no_content }
      end
    else
      redirect_back(fallback_location: root_path, notice: 'Please select User')
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.require(:food).permit(:id, :assigned_user, :name, :food_type, :user_type, :number_of_plate, :status, :email, :phone, :address, :description, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # before_action :authenticate_user!

  def home
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController 
  def create
    rtn = super
    sign_in(resource.type.underscore, resource.type.constantize.send(:find, resource.id)) unless resource.type.nil?
    rtn
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hide_sidebar?
    (controller_name == 'pages') || (controller_name == 'registrations') || ((controller_name == 'sessions') && action_name == 'new')
  end
  def active_class(link_path)
    return unless request.path.include?(link_path.to_s)
		'active'
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/base/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <span class="navbar-brand" href="/"><h3 class="logo">Feed The Needy</h3></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-md-auto">
        <li class="nav-item  <%= active_class(:home) %>">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item <%= active_class(:about) %>">
          <a class="nav-link" href="/about">About</a>
        </li>
        <% if current_user.present? %>
        <li class="nav-item <%= active_class(:dashboards) %>">
          <a class="nav-link" href="/dashboards">Dashboard</a>
        </li>
        <li class="nav-item <%= active_class(:food) %>">
          <a class="nav-link" href="/foods">Food</a>
        </li>

        <li class="nav-item">
          <%= link_to "Sign Out".html_safe, destroy_user_session_path, method: :delete, class:"btn btn-danger" %>
        </li>
        <% end %>
        <% if !current_user.present? %>

        <li class="nav-item">
          <%= link_to  "Contact", new_doner_registration_path, method: :get, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to  "Login", new_user_session_path, method: :get, class:"btn btn-primary" %>
        </li>
        <% end %>

      </ul>

    </div>
  </div>
</nav>

app/views/dashboards/index.html.erb
<section class="hero">
  <div class="container">
    <div class="row">
      <div class="col-sm-7">
        <div class="d-flex h-100 pr-md-5">
          <div class="align-self-center section-info">
            <h1>Dashboard</h1>
            <p><%= current_user.first_name %></p>
          </div>

        </div>
      </div>
      <div class="col-sm-5">
        <div class="hero-bg h-100"></div>
      </div>
    </div>
  </div>
</section>
<section class="highlight-card">
  <div class="container">
    <div class="row">
      <div class="card-columns">
        <% if current_user.super_admin? %>
        <div class="card border-dark mb-3" style="max-width: 36rem;">
          <div class="card-header">Total food list (Veg)</div>
          <div class="card-body text-dark">
            <h5 class="card-title"><%= @foods.where(food_type: 'Veg').count %></h5>
          </div>
        </div>
        <% end %>
        <div class="card border-dark mb-3" style="max-width: 36rem;">
          <div class="card-header">Total food list (Non Veg)</div>
          <div class="card-body text-dark">
            <h5 class="card-title"><%= @foods.where(food_type: 'Non_veg').count %></h5>
          </div>
        </div>
        <div class="card border-dark mb-3" style="max-width: 36rem;">
          <div class="card-header">Todays request</div>
          <div class="card-body text-dark">
            <h5 class="card-title"><%= @foods.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).count %></h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/foods/_assign_form.html.erb
<%= form_with(model: food, local: true, url: '/assign') do |f| %>
<% if food.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(food.errors.count, "error") %> prohibited this request from being saved:</h2>

  <ul>
    <% food.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row">
  <div class="col-sm-8">
    <div class="form-group">
      <label for="">Select User to Donate</label>
      <%= f.select(:assigned_user, Food.where(user_type: 'Request').pluck(:name), {}, { class: 'form-control' }) %>
    </div>
  </div>
</div>
<%= f.hidden_field :id, value: food.id %>


<div class="form-group">
  <button class="btn btn-primary submit-btn">Submit</button>
</div>

<% end %>

app/views/foods/_form.html.erb
<%= form_with(model: food, local: true) do |f| %>
<% if food.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(food.errors.count, "error") %> prohibited this request from being saved:</h2>

  <ul>
    <% food.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row">
  <div class="col-sm-6">
    <div class="form-group">
      <label for="">Type</label>
      <%= f.select(:user_type, [ 'Donate','Request' ], {}, { class: 'form-control' }) %>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="form-group">
      <label for="">Name</label>
      <%= f.text_field :name, autofocus: true, autocomplete: "name", class:"form-control", placeholder:"Contact person name" %>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="form-group">
      <label for="">Phone</label>
      <%= f.text_field :phone, autofocus: true, autocomplete: "phone", class:"form-control", placeholder:"Phone number" %>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="form-group">
      <label for="">Email</label>
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control", placeholder:"Email" %>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="form-group">
      <label for="">Address</label>
      <%= f.text_field :address, autofocus: true, autocomplete: "address", class:"form-control", placeholder:"Enter full address" %>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="form-group">
      <label for="">Description</label>
      <%= f.text_area :description, autofocus: true, autocomplete: "description", class:"form-control", placeholder:"Enter description" %>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="form-group">
      <label for="">Food Type</label>
      <%= f.select(:food_type, [ 'Veg','Non_veg', 'Both' ], {}, { class: 'form-control' }) %>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="form-group">
      <label for="">Number Of Plates</label>
      <%= f.text_field :number_of_plate, autofocus: true, autocomplete: "number_of_plate", class:"form-control", placeholder:"Number Of plates" %>
    </div>
  </div>
</div>

<%= f.hidden_field :user_id, value: current_user.id %>


<div class="form-group">
  <button class="btn btn-primary submit-btn">Submit</button>
</div>

<% end %>

app/views/foods/assign.html.erb
<%= render 'assign_form', food: @food %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<div class="container mt-4">
  <div class="">
    <div class="d-flex">
      <div>
        <h1>Foods</h1>
      </div>
      <div class="ml-auto">
        <%= link_to 'New Food', new_food_path, class: 'btn btn-primary' %>
      </div>
    </div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Phone</th>
          <th scope="col">Address</th>
          <th scope="col">User Type</th>
          <th scope="col">Food Type</th>
          <th scope="col">Status</th>
          <th scope="col">Assigned User</th>
          <th scope="col" colspan="3"> ACTIONS</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.phone %></td>
          <td><%= food.address %></td>
          <td><%= food.user_type %></td>
          <td><%= food.food_type %></td>
          <td><%= food.status ? 'assigned' : 'pending' %></td>
          <td><%= food.assigned_user %></td>
          <td><%= link_to 'Show', food, class: 'btn btn-outline-secondary btn-small' %></td>
          <td><%= link_to 'Edit', edit_food_path(food), class: 'btn btn-outline-primary btn-small' %></td>
          <td><%= link_to 'Destroy', food, class: 'btn btn-outline-danger btn-small', method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% if !food.status && (food.user_type == 'Donate') && current_user.super_admin? %>
          <td><%= link_to 'Assign', assign_path(:id => food.id), class: 'btn btn-outline-success btn-small' %></td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/foods/new.html.erb
<div class="container">
  <div class="row align-items-center">
    <div class="col-6 mx-auto">
      <div class="jumbotron">
        <h1>Add Food Details</h1>
        <%= render 'form', food: @food %>
        <%= link_to 'Back', foods_path %>
      </div>
    </div>
  </div>
</div>

app/views/foods/show.html.erb
<section class="hero">
  <div class="container">
    <div class="row">
      <div class="col-sm-7">
        <div class="d-flex h-100 pr-md-5">
          <div class="align-self-center section-info">
            <h3>Food Detail</h3>
          </div>

        </div>
      </div>
      <div class="col-sm-5">
        <div class="hero-bg h-100"></div>
      </div>
    </div>
  </div>
</section>

<section class="highlight-card">
  <div class="container">
    <div class="">
      <p>
        <strong>Name:</strong>
        <%= @food.name %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= @food.email %>
      </p>

      <p>
        <strong>Phone:</strong>
        <%= @food.phone %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @food.address %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @food.description %>
      </p>

      <p>
        <strong>User:</strong>
        <%= @food.user.first_name %>
      </p>
      <p>
        <strong>Food Type:</strong>
        <%= @food.food_type %>
      </p>
      <p>
        <strong>User Type:</strong>
        <%= @food.user_type %>
      </p>
      <p>
        <strong>Number of plates:</strong>
        <%= @food.number_of_plate %>
      </p>
      <p>
        <strong>Status:</strong>
        <%= @food.status ? 'assigned' : 'pending' %>
      </p>

      <%= link_to 'Edit', edit_food_path(@food) %> |
      <%= link_to 'Back', foods_path %>

    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>App</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>

  <%= render "base/header" %>
  <%= yield %>
</body>

</html>

app/views/pages/about.html.erb
<section class="hero">
  <div class="container">
    <div class="row">
      <div id="demo" class="carousel slide py-4" data-ride="carousel">

        <!-- Indicators -->
        <ul class="carousel-indicators">
          <li data-target="#demo" data-slide-to="0" class="active"></li>
          <li data-target="#demo" data-slide-to="1"></li>
          <li data-target="#demo" data-slide-to="2"></li>
        </ul>

        <!-- The slideshow -->
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="<%= asset_path('hunger.jpg') %>" alt="Los Angeles" width="1100" height="500">
          </div>
          <div class="carousel-item">
            <img src="<%= asset_path('hunger.jpg') %>" alt="Chicago" width="1100" height="500">
          </div>
          <div class="carousel-item">
            <img src="<%= asset_path('hunger.jpg') %>" alt="New York" width="1100" height="500">
          </div>
        </div>

        <!-- Left and right controls -->
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
          <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
          <span class="carousel-control-next-icon"></span>
        </a>
      </div>
    </div>
  </div>
</section>
<section class="hero">
  <div class="container">
    <div class="row">
      <div class="col-sm-7">
        <div class="d-flex h-100 pr-md-5">
          <div class="align-self-center section-info">
            <h1>About Us</h1>
            <p>We are the member of an Indian NGO’s to curb food wastage: Taking from the wedding or any function and giving to the needy people. We are located in Bangalore</p>
          </div>

        </div>
      </div>
      <div class="col-sm-5">
        <div class="hero-bg h-100"></div>
      </div>
    </div>
  </div>
</section>


<section class="highlight-card">
  <div class="container">
    <div class="row">

      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <img src="<%= asset_path('foodwaste.jpg') %>" class="img-responsive w-100">
          </div>
        </div>
      </div>


      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <img src="<%= asset_path('hunger.jpg') %>" class="img-responsive w-100">
          </div>
        </div>
      </div>

    </div>
  </div>
</section>

app/views/pages/home.html.erb
<section class="hero">
  <div class="container">
    <div class="row">
      <div class="col-sm-7">
        <div class="d-flex h-100 pr-md-5">
          <div class="align-self-center section-info">
            <h1>Lorem ipsum salet doler itesum ipsum salet doler</h1>
            <p>You may also utilize dropdowns in your navbar nav. Dropdown menus require a wrapping element for positioning, so be sure to use separate and nested elements for .nav-item and .nav-link as shown below.</p>

          </div>

        </div>
      </div>
      <div class="col-sm-5">
        <div class="hero-bg h-100"></div>
      </div>
    </div>
  </div>
</section>


<section class="highlight-card">
  <div class="container">
    <div class="row">

      <div class="col-sm-6">
        <div class="card bg-primary">
          <div class="card-body text-white p-5">
            <h1>Lorem Ipsum</h1>
            <p>You may also utilize dropdowns in your navbar nav. Dropdown menus require a wrapping element for positioning, so be sure to use separate and nested elements for .nav-item and .nav-link as shown below.</p>

          </div>
        </div>
      </div>


      <div class="col-sm-6">
        <div class="card">
          <div class="card-body text-primary p-5">
            <h1>Lorem Ipsum</h1>
            <p>You may also utilize dropdowns in your navbar nav. Dropdown menus require a wrapping element for positioning, so be sure to use separate and nested elements for .nav-item and .nav-link as shown below.</p>

          </div>
        </div>
      </div>

    </div>
  </div>
</section>